"""add date column to expenses

Revision ID: cf96e7c18f8d
Revises: f4de6754ef36
Create Date: 2025-06-20 00:32:27.878156

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf96e7c18f8d"
down_revision: Union[str, Sequence[str], None] = "f4de6754ef36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenses", "date")
    # ### end Alembic commands ###
